const dataTypeA = {
  "labels": [
    "(Sport) utility vehicle",
    "2-wheeled motorcycle",
    "All-terrain vehicle / all-terrain cycle (ATV/ATC)",
    "Autocycle",
    "Cargo van",
    "Motor home",
    "Passenger car",
    "Passenger van (less than 9 seats)",
    "Pickup",
    "Snowmobile",
    "Truck tractor",
    "15-passenger van",
    "3-wheeled motorcycle",
    "9- or 12-passenger van",
    "Construction equipment (backhoe, bulldozer, etc.)",
    "Farm equipment (tractor, combine, harvester, etc.)",
    "Golf Cart",
    "Low Speed Vehicle",
    "Mini-bus",
    "Moped or motorized bicycle",
    "Motorcoach",
    "Other",
    "Other bus / large passenger vehicle",
    "Other truck",
    "Recreational off-highway vehicles (ROV)",
    "School bus",
    "Single-unit truck",
    "Transit bus"
  ],
  "datasets": [
    {
      "label": "Alcohol Involved",
      "data": [
        6,
        1,
        1,
        1,
        14,
        3,
        5,
        1,
        3,
        4,
        3,
        3,
        3,
        1,
        8,
        2,
        54,
        3,
        16,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "borderColor": "rgba(75, 192, 192, 1)",
      "backgroundColor": "rgba(75, 192, 192, 0.2)"
    },
    {
      "label": "Not Alcohol Involved",
      "data": [
        633,
        197,
        39,
        17,
        1557,
        606,
        0,
        1,
        0,
        4,
        3,
        0,
        3,
        0,
        8,
        2,
        0,
        3,
   
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "borderColor": "rgba(255, 99, 132, 1)",
      "backgroundColor": "rgba(255, 99, 132, 0.2)"
    }
  ]
};

export default dataTypeA;