const data = {
  labels: [
    "(Sport) utility vehicle",
    "2-wheeled motorcycle",
    "All-terrain vehicle / all-terrain cycle (ATV/ATC)",
    "Cargo van",
    "Passenger car",
    "Passenger van (less than 9 seats)",
    "Pickup",
    "Single-unit truck",
    "Truck tractor",
    "15-passenger van",
    "3-wheeled motorcycle",
    "9- or 12-passenger van",
    "Autocycle",
    "Construction equipment (backhoe, bulldozer, etc.)",
    "Farm equipment (tractor, combine, harvester, etc.)",
    "Golf Cart",
    "Low Speed Vehicle",
    "Moped or motorized bicycle",
    "Motor home",
    "Motorcoach",
    "Other",
    "Other bus / large passenger vehicle",
    "Other truck",
    "Recreational off-highway vehicles (ROV)",
    "School bus",
    "Snowmobile",
  ],
  datasets: [
    {
      label: "Drug Type A Involved",
      data: [125, 3, 2, 5, 344, 11, 120, 4, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 37, 0, 23, 0, 6, 2],
      borderColor: "rgba(75, 192, 192, 1)",
      backgroundColor: "rgba(75, 192, 192, 0.2)",
    },
    {
      label: "Drug Type B Involved",
      data: [2786, 423, 69, 81, 7107, 289, 2237, 102, 186, 3, 5, 1, 3, 10, 12, 9, 1, 7, 3, 1, 0, 1, 7, 0, 0, 0],
      borderColor: "rgba(255, 99, 132, 1)",
      backgroundColor: "rgba(255, 99, 132, 0.2)",
    },
  ],
};

export default data;
