const Fatal_cities = [
  { "city": "ABERDEEN", "Fatalities": 0 },
  { "city": "BATESVILLE", "Fatalities": 0 },
  { "city": "BAY SPRINGS", "Fatalities": 0 },
  { "city": "BELMONT", "Fatalities": 0 },
  { "city": "BILOXI", "Fatalities": 1 },
  { "city": "BOLTON", "Fatalities": 0 },
  { "city": "BOONEVILLE", "Fatalities": 0 },
  { "city": "BRANDON", "Fatalities": 0 },
  { "city": "BROOKHAVEN", "Fatalities": 0 },
  { "city": "BROOKSVILLE", "Fatalities": 0 },
  { "city": "CALHOUN city", "Fatalities": 0 },
  { "city": "CANTON", "Fatalities": 0 },
  { "city": "CARTHAGE", "Fatalities": 1 },
  { "city": "CLARKSDALE", "Fatalities": 0 },
  { "city": "CLEVELAND", "Fatalities": 0 },
  { "city": "CLINTON", "Fatalities": 0 },
  { "city": "COLUMBUS", "Fatalities": 1 },
  { "city": "CORINTH", "Fatalities": 0 },
  { "city": "D'IBERVILLE", "Fatalities": 0 },
  { "city": "Did not occur within city limits", "Fatalities": 50 },
  { "city": "DURANT", "Fatalities": 0 },
  { "city": "FLORENCE", "Fatalities": 0 },
  { "city": "GLOSTER", "Fatalities": 1 },
  { "city": "GREENVILLE", "Fatalities": 0 },
  { "city": "GREENWOOD", "Fatalities": 0 },
  { "city": "GRENADA", "Fatalities": 0 },
  { "city": "GULFPORT", "Fatalities": 0 },
  { "city": "HATTIESBURG", "Fatalities": 0 },
  { "city": "HERNANDO", "Fatalities": 0 },
  { "city": "HOLLY SPRINGS", "Fatalities": 0 },
  { "city": "INDIANOLA", "Fatalities": 0 },
  { "city": "JACKSON", "Fatalities": 1 },
  { "city": "LAUREL", "Fatalities": 0 },
  { "city": "LEARNED", "Fatalities": 0 },
  { "city": "LELAND", "Fatalities": 0 },
  { "city": "LEXINGTON", "Fatalities": 0 },
  { "city": "LONG BEACH", "Fatalities": 0 },
  { "city": "LUCEDALE", "Fatalities": 0 },
  { "city": "MACON", "Fatalities": 0 },
  { "city": "MADISON", "Fatalities": 1 },
  { "city": "MAGEE", "Fatalities": 0 },
  { "city": "MAGNOLIA", "Fatalities": 0 },
  { "city": "MCCOMB", "Fatalities": 0 },
  { "city": "MENDENHALL", "Fatalities": 0 },
  { "city": "MERIDIAN", "Fatalities": 1 },
  { "city": "MONTICELLO", "Fatalities": 0 },
  { "city": "MORTON", "Fatalities": 3 },
  { "city": "MOSS POINT", "Fatalities": 0 },
  { "city": "MOUND BAYOU", "Fatalities": 0 },
  { "city": "NATCHEZ", "Fatalities": 1 },
  { "city": "OLIVE BRANCH", "Fatalities": 0 },
  { "city": "Other", "Fatalities": 1 },
  { "city": "OXFORD", "Fatalities": 0 },
  { "city": "PASCAGOULA", "Fatalities": 0 },
  { "city": "PASS CHRISTIAN", "Fatalities": 0 },
  { "city": "PEARL", "Fatalities": 0 },
  { "city": "PICAYUNE", "Fatalities": 0 },
  { "city": "RAYMOND", "Fatalities": 0 },
  { "city": "RIDGELAND", "Fatalities": 0 },
  { "city": "SALTILLO", "Fatalities": 0 },
  { "city": "SENATOBIA", "Fatalities": 1 },
  { "city": "SHANNON", "Fatalities": 0 },
  { "city": "SOUTHAVEN", "Fatalities": 1 },
  { "city": "STARKVILLE", "Fatalities": 0 },
  { "city": "SUMMIT", "Fatalities": 0 },
  { "city": "TCHULA", "Fatalities": 0 },
  { "city": "TERRY", "Fatalities": 0 },
  { "city": "TUPELO", "Fatalities": 1 },
  { "city": "UTICA", "Fatalities": 0 },
  { "city": "VARDAMAN", "Fatalities": 0 },
  { "city": "WATER VALLEY", "Fatalities": 0 },
  { "city": "WESSON", "Fatalities": 1 },
  { "city": "WIGGINS", "Fatalities": 0 },
  { "city": "WINONA", "Fatalities": 0 },
  { "city": "WOODVILLE", "Fatalities": 0 },
  { "city": "YAZOO city", "Fatalities": 0 }
]


export default Fatal_cities ; 